blockRadius: 3
durabilityLostPerSheep: 2 # Minecraft default is 1. Set to 0 to disable
radiusFromSheep: true # If the radius is measured from the sheep or the player
finishAfterBreaking: true # If shears break, this will determine whether to stop or finish shearing nearby sheep

# The range that determines the possible amount of wool to drop from *nearby sheep*
# Does not include the sheep clicked to shear. Vanilla is 1-4
minimumWoolDroppedFromNearbySheep: 1 # Inclusive
maximumWoolDroppedFromNearbySheep: 4 # Exclusive