blockRadius: 3
shearsTakeDamage: true # For every sheep sheared, if true, apply durabilityLostPerSheep to the shears.
durabilityLostPerSheep: 2 # Minecraft default is 1 but this plugin is so good it deserves a 2/2 (which also happens to = 1 but anyways)
