name: EasyShearing
version: '${project.version}'
main: me.grovre.easyshearing.EasyShearing
api-version: 1.19.2
authors: [ PoptartFromPluto ]
description: Shears all animals of that type in a 5 block radius
website: https://github.com/grovre
